const express = require('express')
const router = express.Router()
const multer = require('multer')
const signHandler = require('../router_handler/sign')
const artHandler = require('../router_handler/article')
const cmtHandler = require('../router_handler/comment')
const picHandler = require('../router_handler/pic')
router.post('/reg',signHandler.reg)
router.post('/log',signHandler.log)
router.get('/artlist',artHandler.artList)
router.get('/cmtlist',cmtHandler.cmtList)
router.get('/piclist',picHandler.picList)
module.exports = router